[pyprland]
plugins = ["scratchpads", "wallpapers", "layout_center", "workspaces_follow_focus"]

[wallpapers]
unique = true # set a different wallpaper for each screen
path = "~/Pictures/wallpapers/"
interval = 30 # change every half hour
extensions = ["jpg", "jpeg", "png"]
recurse = true
# hyprpaper
# command = 'hyprctl hyprpaper wallpaper "[],[file]"'
command = 'hyprctl hyprpaper preload "[file]" && hyprctl hyprpaper wallpaper "[output],[file]"'

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.bluetooth]
animation = "fromRight"
command = "blueman-manager"
class = ".blueman-manager-wrapped"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
process_tracking = false
match_by = "initialClass"
initialClass = "Spotify Premium"
size = "90% 90%"
unfocus = "hide"
lazy = true

[layout_center]
next = "hy3:movefocus r"
prev = "hy3:movefocus l"
next2 = "hy3:movefocus d"
prev2 = "hy3:movefocus u"

[workspaces_follow_focus]
