[piri.plugins]
empty = true

[empty.terminal]
command = "wezterm"

[empty.browser]
command = "zen-beta"

[empty.spotify]
command = "spotify"

[empty.discord]
command = "discordcanary"

[empty.explorer]
command = "dolphin"

[empty.t3code]
command = "bash -lc 'pgrep -u \"$USER\" -x t3code >/dev/null || exec t3code'"

[empty.vscode]
command = "code"

[empty.sioyek]
command = "sioyek"

[empty.zotero]
command = "zotero"

[empty.scratch]
command = "wezterm"

[terminal.piri]
auto_width = ["100%", "50%"]
auto_fill = true             # Enable automatic alignment
auto_maximize = true         # Automatic maximization
