[piri.plugins]
empty = true
sticky = true
workspace_rule = true

[empty.terminal]
command = "wezterm"

[empty.browser]
command = "zen-beta"

[empty.chat]
command = "helium"

[empty.spotify]
command = "spotify"

[empty.discord]
command = "discordcanary"

[empty.explorer]
command = "dolphin"

[empty.agents]
# command = "bash -lc 'pgrep -u \"$USER\" -x t3code >/dev/null || exec t3code'"
command = "bash -lc 'pgrep -u \"$USER\" -x codex-desktop >/dev/null || exec codex-desktop'"

[empty.vscode]
command = "code"

[empty.sioyek]
command = "sioyek"

[empty.zotero]
command = "zotero"

[empty.scratch]
command = "wezterm"
